%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
data_dir: /Users/fanhongchang/Downloads/rgbd_dataset_freiburg1_xyz
time_dir: /Users/fanhongchang/Downloads/rgbd_dataset_freiburg1_xyz/rgb.txt
# camera intrinsics
#camera.fx: 517.306408
#camera.fy: 516.469215
#camera.cx: 318.643040
#camera.cy: 255.313989
#
#camera.k1: 0.262383
#camera.k2: -0.953104
#camera.p1: -0.005358
#camera.p2: 0.002628
#camera.k3: 1.163314
camera.fx: 525.0
camera.fy: 525.0
camera.cx: 319.5
camera.cy: 239.5
#
#camera.k1: 0.262383
#camera.k2: -0.953104
#camera.p1: -0.005358
#camera.p2: 0.002628
#camera.k3: 1.163314

num_features: 150
num_features_init: 50
num_features_tracking: 50

# initialize
init.window_size: 4
init.min_good_matches: 30
init.min_translation: 20

track.min_translation: 1
track.max_translation: 8

#init.min_good_matches: 20